In [44]:

import numpy as np
import pandas as pd
# Import Data
results_dataframe = pd.read_csv("archive-3/results.csv")
circuits_dataframe = pd.read_csv("archive-3/circuits.csv")
drivers_dataframe = pd.read_csv("archive-3/drivers.csv")
races_dataframe = pd.read_csv("archive-3/races.csv")
constructor_dataframe = pd.read_csv("archive-3/constructors.csv")
lap_times_dataframe = pd.read_csv("archive-3/lap_times.csv")

In [45]:

# Prints Results Data Frame
results_dataframe.head()# Prints Drivers Data Frame
drivers_dataframe.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [26]:
# Join Data Frames
driver_result_dataframe = pd.merge(results_dataframe,drivers_dataframe,on="driverId")
race_result_dataframe = pd.merge(driver_result_dataframe,races_dataframe,on="raceId")
complete_race_data_dataframe = pd.merge(race_result_dataframe,constructor_dataframe,on="constructorId")

complete_race_data_dataframe.head()

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,...,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,constructorRef,name_y,nationality_y,url
0,1,18,1,1,22,1,1,1,1,10.0,...,\N,\N,\N,\N,\N,\N,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,5,18,5,1,23,3,5,5,5,4.0,...,\N,\N,\N,\N,\N,\N,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
2,27,19,1,1,22,9,5,5,5,4.0,...,\N,\N,\N,\N,\N,\N,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
3,25,19,5,1,23,8,3,3,3,6.0,...,\N,\N,\N,\N,\N,\N,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
4,57,20,1,1,22,3,13,13,13,0.0,...,\N,\N,\N,\N,\N,\N,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren

In [28]:
complete_race_data_dataframe = complete_race_data_dataframe.drop (columns=["url_x","url_y","name_y","nationality_y","url","time_y"])
complete_race_data_dataframe.head()

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,...,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,constructorRef
0,1,18,1,1,22,1,1,1,1,10.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,mclaren
1,5,18,5,1,23,3,5,5,5,4.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,mclaren
2,27,19,1,1,22,9,5,5,5,4.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,mclaren
3,25,19,5,1,23,8,3,3,3,6.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,mclaren
4,57,20,1,1,22,3,13,13,13,0.0,...,\N,\N,\N,\N,\N,\N,\N,\N,\N,mclaren

In [31]:
# Filter & Calculate Results
total_wins = complete_race_data_dataframe[(complete_race_data_dataframe["position"]== "1")] 
total_wins["position_mod"] = total_wins["position"].astype(int)
total_wins = total_wins.groupby(["driverRef","nationality_x"])["position_mod"].sum().reset_index()
total_wins = total_wins.sort_values(by=["position_mod"], ascending=False)
total_wins = total_wins.head(10)

/var/folders/n9/rt0b9w817c3ctp24777l4pbr0000gn/T/ipykernel_20409/3169254076.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_wins["position_mod"] = total_wins["position"].astype(int)

In [57]:
import pandas as pd

# Les inn data fra filer
lap_times_dataframe = pd.read_csv('archive-3/lap_times.csv')
drivers_dataframe = pd.read_csv('archive-3/drivers.csv')
# Les inn data fra drivers.csv-filen
drivers_dataframe = pd.read_csv('archive-3/drivers.csv')

# Referer til driverID-kolonnen
driver_ids = drivers_dataframe['driverID']

# Du kan nå bruke driver_ids som en Series for å få tilgang til driverID-verdiene.

# Vis de første 6 radene av den sammenkoblede tabellen
driver_ids.head(6)

KeyError: 'driverID'